import React from 'react';
import { HourlyPlanItem } from '../types/energy';
import { Calendar } from 'lucide-react';

interface HourlyDispatchTableProps {
  hourlyPlan: HourlyPlanItem[];
}

export const HourlyDispatchTable: React.FC<HourlyDispatchTableProps> = ({
  hourlyPlan,
}) => {
  return (
    <div
      id="hourly-dispatch-table-container"
      className="bg-gradient-to-br from-[#0f1b29]/95 via-[#0b1420]/95 to-[#070d15]/95 border border-[#1d3047]/80 rounded-xl p-5 my-4 shadow-xl shadow-cyan-950/15"
    >
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-2 mb-4">
        <div>
          <div className="flex items-center gap-2">
            <Calendar className="w-4 h-4 text-teal-400" />
            <h3 className="text-base font-bold text-white tracking-tight">
              24-Hour Microgrid Hourly Dispatch Schedule
            </h3>
          </div>
          <p className="text-xs text-[#94a3b8]">
            Optimal hourly dispatch targets generated by the Mixed-Integer Linear Program (MILP).
          </p>
        </div>

        <div className="flex items-center gap-2 text-xs flex-wrap">
          <span className="flex items-center gap-1.5 text-[11px] text-[#94a3b8] bg-[#09121c] px-2.5 py-1 rounded-full border border-[#1a2d40]">
            <span className="w-2.5 h-2.5 rounded-full bg-gradient-to-r from-emerald-500 to-teal-400 inline-block" />
            Off-Peak (&lt;$0.10)
          </span>
          <span className="flex items-center gap-1.5 text-[11px] text-[#94a3b8] bg-[#09121c] px-2.5 py-1 rounded-full border border-[#1a2d40]">
            <span className="w-2.5 h-2.5 rounded-full bg-gradient-to-r from-amber-500 to-yellow-400 inline-block" />
            Mid-Peak ($0.10-$0.25)
          </span>
          <span className="flex items-center gap-1.5 text-[11px] text-[#94a3b8] bg-[#09121c] px-2.5 py-1 rounded-full border border-[#1a2d40]">
            <span className="w-2.5 h-2.5 rounded-full bg-gradient-to-r from-rose-500 to-red-400 inline-block" />
            On-Peak (&gt;$0.25)
          </span>
        </div>
      </div>

      <div className="overflow-x-auto max-h-[460px] overflow-y-auto rounded-xl border border-[#1a2d40] shadow-inner">
        <table className="w-full text-left text-xs text-[#cbd5e1] whitespace-nowrap">
          <thead className="bg-gradient-to-r from-[#0c1624] via-[#101d2d] to-[#0c1624] text-[#94a3b8] sticky top-0 uppercase tracking-wider text-[10px] font-semibold border-b border-[#1a2d40] z-10">
            <tr>
              <th className="py-2.5 px-3">Hour</th>
              <th className="py-2.5 px-3">Grid Rate</th>
              <th className="py-2.5 px-3">Demand (kW)</th>
              <th className="py-2.5 px-3">Solar PV</th>
              <th className="py-2.5 px-3">BESS Charge</th>
              <th className="py-2.5 px-3">BESS Discharge</th>
              <th className="py-2.5 px-3">SoC (%)</th>
              <th className="py-2.5 px-3">Generator</th>
              <th className="py-2.5 px-3">Grid Import</th>
              <th className="py-2.5 px-3 text-right">Cost ($)</th>
            </tr>
          </thead>
          <tbody className="divide-y divide-[#152434]">
            {hourlyPlan.map((row) => {
              const isHighPrice = row.gridPrice >= 0.25;
              const isMedPrice = row.gridPrice >= 0.10 && row.gridPrice < 0.25;

              return (
                <tr
                  key={row.hour}
                  className="hover:bg-[#101f30]/60 transition-colors"
                >
                  <td className="py-2.5 px-3 font-mono font-medium text-white">
                    {row.timeLabel}
                  </td>
                  <td className="py-2.5 px-3">
                    <span
                      className={`px-2 py-0.5 rounded-full text-[10px] font-mono font-semibold ${
                        isHighPrice
                          ? 'bg-gradient-to-r from-rose-950/80 to-red-950/80 text-rose-300 border border-rose-800/40'
                          : isMedPrice
                          ? 'bg-gradient-to-r from-amber-950/80 to-yellow-950/80 text-amber-300 border border-amber-800/40'
                          : 'bg-gradient-to-r from-emerald-950/80 to-teal-950/80 text-teal-300 border border-emerald-800/40'
                      }`}
                    >
                      ${row.gridPrice.toFixed(3)}/kWh
                    </span>
                  </td>
                  <td className="py-2.5 px-3 font-mono text-white">
                    {row.campusDemandKw}
                  </td>
                  <td className="py-2.5 px-3 font-mono text-amber-300">
                    {row.solarUsedKw > 0 ? `${row.solarUsedKw} kW` : '—'}
                  </td>
                  <td className="py-2.5 px-3 font-mono">
                    {row.batteryChargeKw > 0 ? (
                      <span className="text-cyan-400 font-semibold">
                        +{row.batteryChargeKw} kW
                      </span>
                    ) : (
                      <span className="text-[#64748b]">—</span>
                    )}
                  </td>
                  <td className="py-2.5 px-3 font-mono">
                    {row.batteryDischargeKw > 0 ? (
                      <span className="text-teal-300 font-semibold">
                        -{row.batteryDischargeKw} kW
                      </span>
                    ) : (
                      <span className="text-[#64748b]">—</span>
                    )}
                  </td>
                  <td className="py-2.5 px-3">
                    <div className="flex items-center gap-2 w-24">
                      <div className="flex-1 h-2 bg-[#122232] rounded-full overflow-hidden border border-[#1b344c]">
                        <div
                          className="h-full bg-gradient-to-r from-teal-500 to-emerald-400 rounded-full"
                          style={{ width: `${Math.min(100, Math.max(0, row.batterySocPercent))}%` }}
                        />
                      </div>
                      <span className="font-mono text-[11px] text-white">
                        {row.batterySocPercent}%
                      </span>
                    </div>
                  </td>
                  <td className="py-2.5 px-3 font-mono">
                    {row.generatorKw > 0 ? (
                      <span className="text-orange-400 font-semibold">
                        {row.generatorKw} kW
                      </span>
                    ) : (
                      <span className="text-[#64748b]">—</span>
                    )}
                  </td>
                  <td className="py-2.5 px-3 font-mono font-bold text-white">
                    {row.gridImportKw} kW
                  </td>
                  <td className="py-2.5 px-3 font-mono font-bold text-right text-emerald-300">
                    ${row.netCost.toFixed(2)}
                  </td>
                </tr>
              );
            })}
          </tbody>
        </table>
      </div>
    </div>
  );
};
